name: CI
on: 
  push:
    paths: 
      - '**.sbt'
      - 'src/**'
      - 'project/**'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: olafurpg/setup-scala@v13
        with:
          java-version: adopt@1.11
          cache: sbt
      - run: sbt 'formatCheckAll'
