name: Release
on:
  push:
    branches: [main]
    tags: ["*"]
jobs:
  publish:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
        with: 
          fetch-depth: 0
      - uses: olafurpg/setup-scala@v13
      - run: ""
